### PR TITLE
Add script templates for Godot 3.2

### PR DESCRIPTION
**Pull request by Grafcube**
Godot 3.2 allows you to add custom templates in the dropdown when you create a new script and it looks in `res://script_templates` by default. I have made a template that could be better but my intent was to make it easier to get started right away.

This should probably be on a separate branch until Godot 3.2 is fully released. It works on Godot 3.2 Beta 4.

I also think the current stable branch should be updated and published soon.

### CODE REVIEW

**Comment by CodeDarigan** [comment]
I'm not sure on this one. 

I don't like messing around *inside* of anyone's project (outside of the addons folder). This is why when WAT is enabled it sets a pointer to a directory but lets it be up to the user to create it. It is also why WATemp is create to help sandbox off doubles from anything else.

We don't control where script_templates exist so I'd rather not touch it. I wouldn't mind adding a template inside the addons folder people could move to wherever they need it though.

**Comment by CodeDarigan** [comment]
Also (this is likely better suited to an issue) but I plan on releasing the next stable release when Godot 3.2 comes out. WAT itself should be compatible with both versions outside of some additional assertions).

**Comment by Grafcube** [comment]
I moved the templates.

I'm not done with this branch though. I'm working on a menu button that gets the configured template directory and copies the scripts into that directory. If some scripts already exist, it asks the user if they want to overwrite it.

Also Godot doesn't seem to read subdirectories in the templates folder so all templates have to be at the same level.

**Comment by CodeDarigan** [comment]
I didn't consider that this would be accessible via project-settings (I'm assuming that's what you're doing).

I think it might be good to do it on plugin load as well?

Also I've pushed a proper [!3.2 branch](https://github.com/CodeDarigan/WAT/tree/Godot3.2) so I'm going to close this and ask you to move this PR over there.

**Comment by Grafcube** [comment]
I don't think it should be done on plugin load. I think it would be better as an explicit choice especially since the template selection list has the potential to become really long.
But if you think it's better to have it load on activation it would definitely be easier to implement.

**Comment by CodeDarigan** [comment]
I think you're actually right on that in retrospect. This is a nicety not a necessity like WATemp is. Also going to lock this conversation properly this time.

**Pull request closed without merging**
